/**
 * Inline the in-guest relay server into a TypeScript constant.
 *
 *   bun scripts/embed-guest.ts          # regenerate
 *   bun scripts/embed-guest.ts --check  # fail if the generated file is stale
 *
 * Why a generated constant and not `readFileSync`: `startRelay()` uploads the
 * server through the SDK, so the source has to survive being bundled and
 * published as a library. A string constant travels; a file path does not.
 *
 * `src/relay/guest/server.js` is the source of truth. After editing it, run
 * this script and commit both files together — `relay.test.ts` asserts they
 * are in sync.
 */
import { readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"

const SOURCE = fileURLToPath(
  new URL("../src/relay/guest/server.js", import.meta.url),
)
const TARGET = fileURLToPath(
  new URL("../src/relay/guest-source.ts", import.meta.url),
)

/** Make the file safe to sit inside a TypeScript template literal. */
function escapeForTemplate(source: string): string {
  return source
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${")
}

function render(source: string): string {
  return `// GENERATED by scripts/embed-guest.ts — do not edit.
// Source of truth: src/relay/guest/server.js
// Regenerate with: bun scripts/embed-guest.ts

/**
 * The complete handraise relay server, verbatim. Written to the sandbox by
 * \`startRelay()\` and started with the guest's own Node 18 — no install step,
 * no dependencies, no network round trip on the critical path.
 */
export const GUEST_SERVER_JS = \`${escapeForTemplate(source)}\`
`
}

const generated = render(readFileSync(SOURCE, "utf8"))

if (process.argv.includes("--check")) {
  const current = readFileSync(TARGET, "utf8")
  if (current !== generated) {
    console.error("guest-source.ts is stale — run: bun scripts/embed-guest.ts")
    process.exit(1)
  }
  console.log("guest-source.ts is in sync with guest/server.js")
} else {
  writeFileSync(TARGET, generated)
  console.log(`wrote ${TARGET} (${generated.length} bytes)`)
}
