/**
 * Embed test-app/guest/app.js into test-app/guest-source.ts as a string
 * constant, so deploy.ts can upload the test app without reading files at
 * runtime (which would break the moment handraise is consumed from node_modules).
 *
 * Regenerate after every edit to guest/app.js:
 *   bun test-app/embed-app.ts
 *
 * Fail if the checked-in copy is stale (use this in CI):
 *   bun test-app/embed-app.ts --check
 */
const SOURCE_PATH = new URL("./guest/app.js", import.meta.url)
const TARGET_PATH = new URL("./guest-source.ts", import.meta.url)

/** Escape for a template literal: backslashes, backticks, and `${`. */
function escapeTemplate(source: string): string {
  return source
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${")
}

function render(source: string): string {
  return `// Generated by test-app/embed-app.ts from test-app/guest/app.js. Do not edit.
// Regenerate: bun test-app/embed-app.ts

/** The test app's Node source, embedded verbatim for upload into a sandbox. */
export const GUEST_APP_JS = \`${escapeTemplate(source)}\`
`
}

const expected = render(await Bun.file(SOURCE_PATH).text())
const current = await Bun.file(TARGET_PATH)
  .text()
  .catch(() => "")

if (Bun.argv.includes("--check")) {
  if (current !== expected) {
    console.error("guest-source.ts is stale. Run: bun test-app/embed-app.ts")
    process.exit(1)
  }
  console.log("guest-source.ts is up to date")
} else if (current === expected) {
  console.log("guest-source.ts unchanged")
} else {
  await Bun.write(TARGET_PATH, expected)
  console.log(`wrote guest-source.ts (${expected.length} bytes)`)
}
