// Generated by test-app/embed-app.ts from test-app/guest/app.js. Do not edit.
// Regenerate: bun test-app/embed-app.ts

/** The test app's Node source, embedded verbatim for upload into a sandbox. */
export const GUEST_APP_JS = `/**
 * handraise test app — a deterministic username/password + TOTP portal.
 *
 * This is the target the handraise e2e drives: a Solari cloud browser logs in,
 * hits the TOTP step, the agent calls raiseHand(), and a scripted "human" types
 * the code through the handoff UI. Every route is server-rendered and every
 * form is method="post", so the flow works with JavaScript disabled.
 *
 * Runs on Node 18 (the Solari \`base\` template) with ZERO dependencies. ES
 * modules, and deploy.ts uploads it as \`app.mjs\`: this repo is \`"type":
 * "module"\`, /opt/testapp in the sandbox has no package.json at all, and \`.mjs\`
 * is the one extension both agree is ESM.
 *
 * Source of truth: edit THIS file, then run \`bun test-app/embed-app.ts\` to
 * regenerate test-app/guest-source.ts, which deploy.ts uploads to the sandbox.
 *
 * Env:
 *   PORT         listen port                   (default 4000)
 *   TOTP_SECRET  base32 shared secret          (default JBSWY3DPEHPK3PXP)
 *   APP_USER     accepted username             (default ada)
 *   APP_PASS     accepted password             (default solaris)
 *
 * Routes:
 *   GET  /         login form
 *   POST /login    credentials -> 303 /totp + signed pending cookie, or 401
 *   GET  /totp     one input for the 6-digit code
 *   POST /totp     RFC 6238 check (SHA-1, 30s step, +/-1 step) -> 303 /account
 *   GET  /account  "Signed in as <user>" + <h1 data-testid="signed-in">
 *   GET  /qr       behind the session: a QR code for the /verified link
 *   GET  /verified token-gated: the page a scanned code leads to
 *   GET  /transfer one amount + payee form, behind the session
 *   POST /transfer validates, records the transfer -> 303 /account
 *   POST /logout   clears the session -> 303 /
 *   GET  /healthz  200 "ok"
 *
 * The QR pair is what the QR-passthrough e2e drives: a site that asks for a
 * device change, exactly the shape reCAPTCHA's scan-to-verify has. The image
 * cannot be generated here - this file has no dependencies and no encoder - so
 * deploy.ts renders it once the preview URL exists (only then is there an
 * absolute link to encode) and writes it beside this file as qr.json.
 *
 * Env (QR):
 *   QR_FILE      where that JSON lives   (default: qr.json next to this file)
 */
import crypto from "node:crypto"
import fs from "node:fs"
import http from "node:http"

const PORT = Number(process.env.PORT || 4000)
const TOTP_SECRET = process.env.TOTP_SECRET || "JBSWY3DPEHPK3PXP"
const APP_USER = process.env.APP_USER || "ada"
const APP_PASS = process.env.APP_PASS || "solaris"

const BRAND = "Aurora Bank"
/** Signing key for the cookies. Fresh per boot: restarting invalidates sessions. */
const COOKIE_KEY = crypto.randomBytes(32)
const PENDING_COOKIE = "hr_pending"
const SESSION_COOKIE = "hr_session"
/** Carries the last transfer, so /account can show it without server state. */
const TRANSFER_COOKIE = "hr_transfer"
const PENDING_TTL_MS = 5 * 60_000
const SESSION_TTL_MS = 30 * 60_000
const MAX_BODY_BYTES = 8 * 1024
const QR_FILE =
  process.env.QR_FILE || new URL("./qr.json", import.meta.url).pathname

// ---------------------------------------------------------------- TOTP -----

const BASE32_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"

/** Decode an RFC 4648 base32 string (padding and whitespace tolerated). */
function base32Decode(input) {
  const clean = input.replace(/[\\s=]/g, "").toUpperCase()
  const bytes = []
  let buffer = 0
  let bits = 0
  for (const char of clean) {
    const index = BASE32_ALPHABET.indexOf(char)
    if (index === -1) throw new Error(\`invalid base32 character: \${char}\`)
    buffer = (buffer << 5) | index
    bits += 5
    if (bits >= 8) {
      bits -= 8
      bytes.push((buffer >>> bits) & 0xff)
    }
  }
  return Buffer.from(bytes)
}

/** RFC 4226 HOTP, 6 digits, SHA-1. */
function hotp(key, counter) {
  const message = Buffer.alloc(8)
  message.writeUInt32BE(Math.floor(counter / 2 ** 32), 0)
  message.writeUInt32BE(counter >>> 0, 4)
  const mac = crypto.createHmac("sha1", key).update(message).digest()
  const offset = mac.readUInt8(mac.length - 1) & 0x0f
  const truncated = mac.readUInt32BE(offset) & 0x7fffffff
  return String(truncated % 1_000_000).padStart(6, "0")
}

/** RFC 6238 verification: 30-second step, +/-1 step of clock tolerance. */
function verifyTotp(secret, candidate) {
  if (!/^[0-9]{6}$/.test(candidate)) return false
  const key = base32Decode(secret)
  const step = Math.floor(Date.now() / 1000 / 30)
  const candidateBuffer = Buffer.from(candidate, "utf8")
  let matched = false
  for (const drift of [-1, 0, 1]) {
    const expected = Buffer.from(hotp(key, step + drift), "utf8")
    // Constant time, and never short-circuit: every window costs the same.
    if (crypto.timingSafeEqual(expected, candidateBuffer)) matched = true
  }
  return matched
}

// -------------------------------------------------------------- cookies ----

function base64url(buffer) {
  return buffer
    .toString("base64")
    .replace(/\\+/g, "-")
    .replace(/\\//g, "_")
    .replace(/=+$/, "")
}

function sign(payload) {
  const body = base64url(Buffer.from(JSON.stringify(payload), "utf8"))
  const mac = base64url(
    crypto.createHmac("sha256", COOKIE_KEY).update(body).digest(),
  )
  return \`\${body}.\${mac}\`
}

/** Verify signature and expiry. Returns the payload, or null for anything off. */
function unsign(value) {
  if (!value) return null
  const dot = value.lastIndexOf(".")
  if (dot < 1) return null
  const body = value.slice(0, dot)
  const mac = Buffer.from(value.slice(dot + 1), "utf8")
  const expected = Buffer.from(
    base64url(crypto.createHmac("sha256", COOKIE_KEY).update(body).digest()),
    "utf8",
  )
  if (mac.length !== expected.length) return null
  if (!crypto.timingSafeEqual(expected, mac)) return null
  try {
    const payload = JSON.parse(Buffer.from(body, "base64").toString("utf8"))
    if (!payload?.exp || payload.exp < Date.now()) return null
    return payload
  } catch {
    return null
  }
}

function readCookie(req, name) {
  const header = req.headers.cookie
  if (!header) return null
  for (const part of header.split(";")) {
    const eq = part.indexOf("=")
    if (eq === -1) continue
    if (part.slice(0, eq).trim() === name)
      return decodeURIComponent(part.slice(eq + 1).trim())
  }
  return null
}

function isSecureRequest(req) {
  return (
    String(req.headers["x-forwarded-proto"] || "")
      .split(",")[0]
      .trim() === "https"
  )
}

function cookieHeader(req, name, value, maxAgeSeconds) {
  const attributes = [
    "Path=/",
    "HttpOnly",
    "SameSite=Lax",
    \`Max-Age=\${maxAgeSeconds}\`,
  ]
  if (isSecureRequest(req)) attributes.push("Secure")
  return \`\${name}=\${encodeURIComponent(value)}; \${attributes.join("; ")}\`
}

// ----------------------------------------------------------------- HTML ----

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}

const STYLES = \`
  :root { color-scheme: light }
  * { box-sizing: border-box }
  body {
    margin: 0; min-height: 100vh; display: grid; place-items: center;
    background: #f4f6f8; color: #12151a;
    font: 15px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
  }
  .card {
    width: min(360px, calc(100vw - 32px)); background: #fff; padding: 28px;
    border: 1px solid #e4e7eb; border-radius: 12px;
    box-shadow: 0 1px 2px rgba(16,24,40,.04), 0 10px 28px rgba(16,24,40,.06);
  }
  .card.wide { width: min(560px, calc(100vw - 32px)) }
  .brand { display: flex; align-items: center; gap: 8px; font-weight: 600; letter-spacing: -.01em; margin-bottom: 22px }
  .brand span { width: 10px; height: 10px; border-radius: 50%; background: #2f6df6 }
  h1 { font-size: 19px; margin: 0 0 4px; letter-spacing: -.015em }
  .sub { margin: 0 0 20px; color: #5b6472; font-size: 14px }
  .field { margin-bottom: 14px }
  label { display: block; font-size: 13px; font-weight: 500; margin-bottom: 6px }
  input {
    width: 100%; padding: 10px 12px; font-size: 15px; color: inherit; background: #fff;
    border: 1px solid #d4d9df; border-radius: 8px;
  }
  input:focus { outline: 2px solid #2f6df6; outline-offset: -1px; border-color: #2f6df6 }
  .code { text-align: center; letter-spacing: .35em; font-size: 20px; font-variant-numeric: tabular-nums }
  button {
    width: 100%; margin-top: 6px; padding: 11px 12px; font: inherit; font-weight: 500;
    color: #fff; background: #12151a; border: 0; border-radius: 8px; cursor: pointer;
  }
  button:hover { background: #2b3038 }
  .error {
    margin-bottom: 16px; padding: 9px 12px; font-size: 13px;
    color: #9f1239; background: #fef2f2; border: 1px solid #fecdd3; border-radius: 8px;
  }
  .ok {
    display: inline-block; margin-bottom: 16px; padding: 3px 9px; font-size: 12px; font-weight: 500;
    color: #065f46; background: #ecfdf5; border: 1px solid #a7f3d0; border-radius: 999px;
  }
  .foot { margin-top: 18px; font-size: 12px; color: #8b939f; text-align: center }
  .link { width: auto; margin: 0; padding: 0; color: #5b6472; background: none; font-size: 12px; text-decoration: underline }
  .link:hover { background: none; color: #12151a }
\`

function page(title, inner, variant) {
  return \`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>\${escapeHtml(title)} — \${BRAND}</title>
<style>\${STYLES}</style>
</head>
<body>
<main class="card\${variant ? \` \${variant}\` : ""}">
<div class="brand"><span></span>\${BRAND}</div>
\${inner}
<p class="foot">Demo target for handraise. Not a real bank.</p>
</main>
</body>
</html>
\`
}

function errorBox(message) {
  return message
    ? \`<p class="error" data-testid="error" role="alert">\${escapeHtml(message)}</p>\`
    : ""
}

function loginPage(error, username) {
  return page(
    "Sign in",
    \`<h1>Sign in</h1>
<p class="sub">Use your \${BRAND} credentials to continue.</p>
\${errorBox(error)}
<form method="post" action="/login" data-testid="login-form">
  <div class="field">
    <label for="username">Username</label>
    <input id="username" name="username" type="text" autocomplete="username" autocapitalize="none"
           spellcheck="false" value="\${escapeHtml(username || "")}" data-testid="username" required>
  </div>
  <div class="field">
    <label for="password">Password</label>
    <input id="password" name="password" type="password" autocomplete="current-password"
           data-testid="password" required>
  </div>
  <button type="submit" data-testid="login-submit">Continue</button>
</form>\`,
  )
}

function totpPage(error) {
  return page(
    "Two-factor",
    \`<h1>Two-factor authentication</h1>
<p class="sub">Enter the 6-digit code from your authenticator app.</p>
\${errorBox(error)}
<form method="post" action="/totp" data-testid="totp-form">
  <div class="field">
    <label for="code">Authentication code</label>
    <input id="code" name="code" type="text" class="code" inputmode="numeric" autocomplete="one-time-code"
           pattern="[0-9]{6}" maxlength="6" placeholder="000000" data-testid="totp-code" required autofocus>
  </div>
  <button type="submit" data-testid="totp-submit">Verify</button>
</form>\`,
  )
}

function accountPage(username, transfer) {
  const sent = transfer
    ? \`<p class="ok" data-testid="transfer-done">Sent EUR \${escapeHtml(
        transfer.amount,
      )} to \${escapeHtml(transfer.payee)}</p>\`
    : ""
  return page(
    "Account",
    \`<p class="ok" data-testid="verified">Two-factor verified</p>
\${sent}
<h1 data-testid="signed-in">Signed in as \${escapeHtml(username)}</h1>
<p class="sub">Your session is active. Nothing here moves real money.</p>
<p><a class="link" href="/transfer" data-testid="transfer-link">Send a transfer</a></p>
<form method="post" action="/logout">
  <button type="submit" class="link" data-testid="logout">Sign out</button>
</form>\`,
  )
}

/**
 * The step an agent is not supposed to take alone: it fills the form, and a
 * human says yes or no before it presses the button.
 */
function transferPage(error, amount, payee) {
  return page(
    "Transfer",
    \`<h1>Send a transfer</h1>
<p class="sub">The money leaves the account the moment you submit.</p>
\${errorBox(error)}
<form method="post" action="/transfer" data-testid="transfer-form">
  <div class="field">
    <label for="amount">Amount (EUR)</label>
    <input id="amount" name="amount" type="text" inputmode="decimal" placeholder="12430.00"
           value="\${escapeHtml(amount || "")}" data-testid="transfer-amount" required>
  </div>
  <div class="field">
    <label for="payee">Payee</label>
    <input id="payee" name="payee" type="text" autocomplete="off" spellcheck="false"
           value="\${escapeHtml(payee || "")}" data-testid="transfer-payee" required>
  </div>
  <button type="submit" data-testid="transfer-submit">Send transfer</button>
</form>\`,
  )
}

/** What is wrong with this transfer, or null if nothing is. */
function transferProblem(amount, payee) {
  if (!/^[0-9]{1,9}(\\.[0-9]{1,2})?$/.test(amount) || Number(amount) <= 0) {
    return "Enter an amount like 12430.00."
  }
  if (payee.length === 0 || payee.length > 64) return "Enter a payee name."
  return null
}

/**
 * The device-change step. Read fresh on every request and never cached:
 * deploy.ts writes this file after the app is already listening, because the
 * link inside the code is only knowable once the sandbox has a preview URL.
 */
function readQr() {
  try {
    const parsed = JSON.parse(fs.readFileSync(QR_FILE, "utf8"))
    const token = String(parsed?.token ?? "")
    const png = String(parsed?.png ?? "")
    if (token === "" || png === "") return null
    return { token, png }
  } catch {
    return null
  }
}

function qrPage(png) {
  return page(
    "Confirm on another device",
    \`<h1>Confirm on another device</h1>
<p class="sub">Scan this code with the phone you registered. This page will not
continue until you do.</p>
<img data-testid="qr-code" alt="Device confirmation code" width="420" height="420" src="\${escapeHtml(png)}">\`,
    "wide",
  )
}

function verifiedPage() {
  return page(
    "Device confirmed",
    \`<p class="ok" data-testid="verified">Device confirmed</p>
<p class="sub">You can go back to the other screen.</p>\`,
  )
}

function notFoundPage() {
  return page(
    "Not found",
    \`<h1 data-testid="not-found">Page not found</h1><p class="sub">Nothing lives at this address.</p>\`,
  )
}

// ------------------------------------------------------------- plumbing ----

function readBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = []
    let size = 0
    req.on("data", (chunk) => {
      size += chunk.length
      if (size > MAX_BODY_BYTES) {
        reject(new Error("body too large"))
        req.destroy()
        return
      }
      chunks.push(chunk)
    })
    req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")))
    req.on("error", reject)
  })
}

function equalSecret(actual, expected) {
  const a = Buffer.from(actual, "utf8")
  const b = Buffer.from(expected, "utf8")
  if (a.length !== b.length) return false
  return crypto.timingSafeEqual(a, b)
}

function send(res, status, contentType, body, extraHeaders) {
  const headers = Object.assign(
    { "content-type": contentType, "cache-control": "no-store" },
    extraHeaders,
  )
  res.writeHead(status, headers)
  res.end(body)
  return status
}

function redirect(res, location, extraHeaders) {
  return send(
    res,
    303,
    "text/plain; charset=utf-8",
    "",
    Object.assign({ location }, extraHeaders),
  )
}

/** The 2FA step: the pending cookie gets in, the right code gets a session. */
async function routeTotp(req, res, method, event) {
  const pending = unsign(readCookie(req, PENDING_COOKIE))
  event.pending = Boolean(pending)
  if (!pending) return redirect(res, "/")
  if (method === "GET") {
    return send(res, 200, "text/html; charset=utf-8", totpPage(null))
  }
  if (method === "POST") {
    const form = new URLSearchParams(await readBody(req))
    const code = (form.get("code") || "").trim()
    const ok = verifyTotp(TOTP_SECRET, code)
    event.user = pending.user
    event.code_ok = ok
    if (!ok) {
      return send(
        res,
        401,
        "text/html; charset=utf-8",
        totpPage("That code is not valid. Try again."),
      )
    }
    const session = cookieHeader(
      req,
      SESSION_COOKIE,
      sign({ user: pending.user, exp: Date.now() + SESSION_TTL_MS }),
      SESSION_TTL_MS / 1000,
    )
    const clearPending = \`\${PENDING_COOKIE}=; Path=/; HttpOnly; Max-Age=0\`
    return redirect(res, "/account", {
      "set-cookie": [session, clearPending],
    })
  }
  return send(res, 404, "text/html; charset=utf-8", notFoundPage())
}

/** GET shows the form; POST validates it and records it in a signed cookie. */
async function routeTransfer(req, res, method, event) {
  if (method === "GET") {
    const html = transferPage(null, null, null)
    return send(res, 200, "text/html; charset=utf-8", html)
  }
  if (method !== "POST") {
    return send(res, 404, "text/html; charset=utf-8", notFoundPage())
  }
  const form = new URLSearchParams(await readBody(req))
  const amount = (form.get("amount") || "").trim()
  const payee = (form.get("payee") || "").trim()
  const problem = transferProblem(amount, payee)
  event.transfer_ok = problem === null
  if (problem) {
    const html = transferPage(problem, amount, payee)
    return send(res, 400, "text/html; charset=utf-8", html)
  }
  const cookie = cookieHeader(
    req,
    TRANSFER_COOKIE,
    sign({ amount, payee, exp: Date.now() + SESSION_TTL_MS }),
    SESSION_TTL_MS / 1000,
  )
  return redirect(res, "/account", { "set-cookie": cookie })
}

/** The device-change step, behind the session the agent earned with the code. */
function qrRoute(req, res, event) {
  const session = unsign(readCookie(req, SESSION_COOKIE))
  event.signed_in = Boolean(session)
  if (!session) return redirect(res, "/")
  const qr = readQr()
  event.qr_ready = Boolean(qr)
  if (!qr) {
    return send(res, 503, "text/plain; charset=utf-8", "no code deployed yet")
  }
  return send(res, 200, "text/html; charset=utf-8", qrPage(qr.png))
}

/**
 * Where a scanned code leads. Deliberately not behind the session: a real
 * device-change link is opened on a phone that has never seen this site, and
 * the token in it is the whole credential. That is what makes such a link
 * worth passing through a handoff at all.
 */
function verifiedRoute(res, url, event) {
  const qr = readQr()
  const given = url.searchParams.get("token") || ""
  const ok = Boolean(qr) && equalSecret(given, qr.token)
  event.token_ok = ok
  if (!ok) {
    return send(
      res,
      403,
      "text/html; charset=utf-8",
      page(
        "Not confirmed",
        \`<p class="error" data-testid="not-verified" role="alert">That confirmation link is not valid.</p>\`,
      ),
    )
  }
  return send(res, 200, "text/html; charset=utf-8", verifiedPage())
}

async function route(req, res, url, event) {
  const method = req.method || "GET"

  if (url.pathname === "/healthz") {
    return send(res, 200, "text/plain; charset=utf-8", "ok")
  }

  if (url.pathname === "/" && method === "GET") {
    return send(res, 200, "text/html; charset=utf-8", loginPage(null, null))
  }

  if (url.pathname === "/login" && method === "POST") {
    const form = new URLSearchParams(await readBody(req))
    const username = form.get("username") || ""
    const password = form.get("password") || ""
    // Both comparisons always run: no short-circuit, no timing hint about which failed.
    const userOk = equalSecret(username, APP_USER)
    const passOk = equalSecret(password, APP_PASS)
    const ok = userOk && passOk
    event.user = username
    event.credentials_ok = ok
    if (!ok) {
      return send(
        res,
        401,
        "text/html; charset=utf-8",
        loginPage("Wrong username or password.", username),
      )
    }
    const cookie = cookieHeader(
      req,
      PENDING_COOKIE,
      sign({ user: username, exp: Date.now() + PENDING_TTL_MS }),
      PENDING_TTL_MS / 1000,
    )
    return redirect(res, "/totp", { "set-cookie": cookie })
  }

  if (url.pathname === "/totp") {
    return routeTotp(req, res, method, event)
  }

  if (url.pathname === "/account" && method === "GET") {
    const session = unsign(readCookie(req, SESSION_COOKIE))
    event.signed_in = Boolean(session)
    if (!session) return redirect(res, "/")
    event.user = session.user
    const transfer = unsign(readCookie(req, TRANSFER_COOKIE))
    return send(
      res,
      200,
      "text/html; charset=utf-8",
      accountPage(session.user, transfer),
    )
  }

  if (url.pathname === "/transfer") {
    const session = unsign(readCookie(req, SESSION_COOKIE))
    event.signed_in = Boolean(session)
    if (!session) return redirect(res, "/")
    event.user = session.user
    return routeTransfer(req, res, method, event)
  }

  if (url.pathname === "/qr" && method === "GET") {
    return qrRoute(req, res, event)
  }

  if (url.pathname === "/verified" && method === "GET") {
    return verifiedRoute(res, url, event)
  }

  if (url.pathname === "/logout" && method === "POST") {
    return redirect(res, "/", {
      "set-cookie": [
        \`\${SESSION_COOKIE}=; Path=/; HttpOnly; Max-Age=0\`,
        \`\${TRANSFER_COOKIE}=; Path=/; HttpOnly; Max-Age=0\`,
      ],
    })
  }

  return send(res, 404, "text/html; charset=utf-8", notFoundPage())
}

const server = http.createServer((req, res) => {
  const startedAt = Date.now()
  const url = new URL(req.url || "/", "http://localhost")
  const event = {
    evt: "http_request",
    method: req.method,
    path: url.pathname,
    ua: req.headers["user-agent"] || null,
  }
  route(req, res, url, event)
    .then((status) => {
      event.status = status
    })
    .catch((error) => {
      event.status = 500
      event.error = error instanceof Error ? error.message : String(error)
      if (!res.headersSent)
        send(res, 500, "text/plain; charset=utf-8", "internal error")
    })
    .finally(() => {
      event.duration_ms = Date.now() - startedAt
      console.log(JSON.stringify(event))
    })
})

server.listen(PORT, "0.0.0.0", () => {
  console.log(
    JSON.stringify({
      evt: "listening",
      port: PORT,
      user: APP_USER,
      brand: BRAND,
    }),
  )
})
`
